packages:
  - 'packages/*'
  - 'examples/react/*'
  - 'examples/react/router-monorepo-react-query/packages/*'
  - 'examples/react/router-monorepo-simple/packages/*'
  - 'e2e/react-router/*'
  - 'e2e/start/*'
  - 'e2e/create-start'
